//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataFirst.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UserManagementEntities : DbContext
    {
        public UserManagementEntities()
            : base("name=UserManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CourseLevel> CourseLevels { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<UserCourse> UserCourses { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<CourseEnrollments_Result> CourseEnrollments()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CourseEnrollments_Result>("CourseEnrollments");
        }
    }
}
